version: '3'

services:
  cluster-redis-connection-pool-custom:
    image: redis:latest
    container_name: cluster-redis-connection-pool-custom
    volumes:
      - ./docker/redis/redis.conf:/redis.conf
      - ./docker/redis/entrypoint.sh:/entrypoint.sh
    command: /entrypoint.sh
    #command: sleep 999999
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      redis-connection-pool-custom:
        ipv4_address: 172.31.112.2

networks:
  redis-connection-pool-custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.112.1/24
          gateway: 172.31.112.1
