sqlserver:
  container_name: perf-sqlserver
  image: mcr.microsoft.com/mssql/server:2019-latest
  ports:
    - "1433:1433"
  environment:
    ACCEPT_EULA: 1
    SA_PASSWORD: p@ssw0rd
  volumes:
    - "./init-mssql:/init-mssql"
  command: >
    /bin/bash -c "
      if [[ ! -f /.already_initialized ]]; then
        /opt/mssql/bin/sqlservr --accept-eula &
        while sleep 1; do
          echo 'Watiting for launching mssql...';
          /opt/mssql-tools/bin/sqlcmd -U sa -P \"$$SA_PASSWORD\" -i /dev/stdin <<< 'SELECT name FROM sys.databases;' && break
        done
        while read file; do
          /opt/mssql-tools/bin/sqlcmd -U sa -P \"$$SA_PASSWORD\" -i \"$$file\" || exit 1
        done < <(find /init-mssql/ -type f -name \"*.sql\" | sort)

        touch /.already_initialized;

        pid=$$(ps -ef | grep -P '^mssql\s+\d+\s+1\s+.*sqlservr \-\-accept\-eula$$' | awk '{print $$2}');
        kill $$pid;

        echo \"Waiting to stop process $$pid\";

        wait $$pid;
      fi
      exec /opt/mssql/bin/sqlservr --accept-eula;
    "
