# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
# Multi connection pooling with lettuce will not improbe performance.
# If you specify "spring.redis.jedis" to use jedis, multi connection pooling does not work for some reason...
# See another example to use jedis with multi connection pooling.
spring:
  redis:
    lettuce:
      host: localhost
      port: 6379
      pool:
        max-active: 16
        max-idle: 12
        max-wait: 1000ms
        min-idle: 8
        time-between-eviction-runs: 1
