USE master;

INSERT INTO Persons (Name, MailAddress, City) VALUES
    ('Dorri Evert','devert0@ted.com','87017 Bunker Hill Street'),
    ('Cecilio Romme','cromme1@fc2.com','8698 Jackson Plaza'),
    ('Ernest Giovannazzi','egiovannazzi2@imdb.com','26505 Little Fleur Crossing'),
    ('Desi Braunfeld','dbraunfeld3@hud.gov','0 Eagle Crest Crossing'),
    ('Baillie Summerell','bsummerell4@archive.org','99970 Bartillon Trail'),
    ('Alie Phillipps','aphillipps5@exblog.jp','33716 Mesta Lane'),
    ('Stormie Flexman','sflexman6@springer.com','06 Nevada Lane'),
    ('Evangelin Ellicock','eellicock7@ow.ly','68610 Scott Drive'),
    ('Jandy Thorogood','jthorogood8@devhub.com','36490 Brickson Park Court'),
    ('Florri Seabright','fseabright9@go.com','72 Heath Hill'),
    ('Lynelle Drakeford','ldrakeforda@toplist.cz','54 Village Green Circle'),
    ('Shanan Danson','sdansonb@imdb.com','8043 Kennedy Circle'),
    ('Leora Peegrem','lpeegremc@bravesites.com','92 Carberry Park'),
    ('Lettie Crumpe','lcrumped@parallels.com','621 Shasta Court'),
    ('Pearla McDill','pmcdille@usatoday.com','15 Boyd Circle'),
    ('Bronnie Musto','bmustof@nymag.com','9 Westport Alley'),
    ('Garik Gauthorpp','ggauthorppg@umn.edu','0649 Paget Hill'),
    ('Rhetta Cooksey','rcookseyh@spiegel.de','02442 Valley Edge Parkway'),
    ('Rubin Dunk','rdunki@disqus.com','7349 Northland Way'),
    ('Junina McComish','jmccomishj@geocities.jp','60010 Melby Circle'),
    ('Nichole Rigate','nrigatek@wufoo.com','87 Sachtjen Place'),
    ('Stephanie Hertwell','shertwelll@bloglovin.com','0379 Graceland Terrace'),
    ('Pia Abbot-Doyle','pdabbotdoylem@mozilla.com','208 Shasta Circle'),
    ('Zachary Billinge','zbillingen@mysql.com','46 Sachs Point'),
    ('Hedvige Spaldin','hspaldino@webmd.com','12 Cordelia Way'),
    ('Wait Braams','wbraamsp@google.pl','52 Park Meadow Junction'),
    ('Veronica Farres','vfarresq@newyorker.com','48 Lerdahl Plaza'),
    ('Martie Aharoni','maharonir@theatlantic.com','35 Southridge Plaza'),
    ('Corbie Brill','cbrills@trellian.com','99580 Starling Alley'),
    ('Marlin Souten','msoutent@wired.com','718 Beilfuss Road'),
    ('Melania Everwin','meverwinu@va.gov','8 Pleasure Plaza'),
    ('Sheena Ffoulkes','sffoulkesv@lycos.com','6 Morningstar Drive'),
    ('Reinald Trudgeon','rtrudgeonw@gov.uk','22 Stuart Court'),
    ('Korella Langshaw','klangshawx@flavors.me','4 Bellgrove Crossing'),
    ('Johnette Lermit','jlermity@nba.com','13 Sullivan Center'),
    ('Cristin Davidsohn','cdavidsohnz@wikispaces.com','0415 Haas Circle'),
    ('Kleon Tolotti','ktolotti10@so-net.ne.jp','788 Ruskin Center'),
    ('Meaghan Reading','mreading11@vimeo.com','8 Lawn Court'),
    ('Ianthe Fenelow','ifenelow12@google.it','57820 Elgar Court'),
    ('Bill Iddy','biddy13@nyu.edu','11773 Annamark Street'),
    ('Sile Brasner','sbrasner14@discovery.com','314 Cordelia Court'),
    ('Archy Fennelow','afennelow15@fc2.com','7116 Lake View Point'),
    ('Hughie Manvelle','hmanvelle16@ft.com','3666 Arkansas Point'),
    ('Analiese Bridgett','abridgett17@live.com','6 Old Gate Junction'),
    ('Jori Folling','jfolling18@reference.com','90 Nancy Way'),
    ('Matthieu Sennett','msennett19@amazon.co.uk','358 Lakewood Trail'),
    ('Pamelina Franceschielli','pfranceschielli1a@upenn.edu','2386 Cody Court'),
    ('Devland Bestar','dbestar1b@ucoz.ru','43188 Graedel Lane'),
    ('Alexandros Concannon','aoconcannon1c@seesaa.net','313 Warbler Trail'),
    ('Lezley Pittham','lpittham1d@ucsd.edu','62 Loftsgordon Way'),
    ('Tristam Armitt','tarmitt1e@desdev.cn','745 Derek Terrace'),
    ('Brandice Sommer','bsommer1f@mozilla.com','2 Debra Lane'),
    ('Edeline Romagnosi','eromagnosi1g@scribd.com','301 Charing Cross Avenue'),
    ('Lanae Ost','lost1h@ycombinator.com','64 Anniversary Drive'),
    ('Guy Sugge','gsugge1i@msn.com','69 Almo Center'),
    ('Aguie Crum','acrum1j@phoca.cz','18877 Forest Drive'),
    ('Lothaire Klauer','lklauer1k@uol.com.br','3 Novick Lane'),
    ('Poppy Kellock','pkellock1l@timesonline.co.uk','02 Fair Oaks Terrace'),
    ('Therese Fominov','tfominov1m@archive.org','82 Doe Crossing Alley'),
    ('Valentine Courteney','vcourteney1n@bing.com','08 Continental Point'),
    ('Lilian Crowcum','lcrowcum1o@printfriendly.com','6 Daystar Street'),
    ('Kaspar Markovic','kmarkovic1p@chron.com','5858 Lillian Street'),
    ('Raf Maccree','rmaccree1q@list-manage.com','9749 Starling Park'),
    ('Chiquita Rushforth','crushforth1r@histats.com','6498 3rd Terrace'),
    ('Georgine Currie','gcurrie1s@sourceforge.net','82 Schmedeman Place'),
    ('Aldwin McKevany','amckevany1t@nbcnews.com','4 Packers Parkway'),
    ('Ignace Leggan','ileggan1u@bloomberg.com','00983 Morningstar Lane'),
    ('Tulley Davet','tdavet1v@newyorker.com','2608 Lerdahl Park'),
    ('Kamilah Dalwood','kdalwood1w@soundcloud.com','0973 Orin Park'),
    ('Egor Witcherley','ewitcherley1x@gravatar.com','2294 Doe Crossing Center'),
    ('Dun Mallen','dmallen1y@etsy.com','249 Veith Alley'),
    ('Cully Sweedland','csweedland1z@skyrock.com','4 Walton Pass'),
    ('Winnah Hassewell','whassewell20@mtv.com','43 Lyons Crossing'),
    ('Alfi Castagnasso','acastagnasso21@list-manage.com','11461 Hollow Ridge Place'),
    ('Kayne Tangye','ktangye22@uol.com.br','3 Elka Point'),
    ('Shirley Duffitt','sduffitt23@t.co','3898 Packers Parkway'),
    ('Felecia Rowswell','frowswell24@barnesandnoble.com','17 Sage Street'),
    ('Griffy Heinecke','gheinecke25@unblog.fr','0157 Shoshone Place'),
    ('Adolf Paolini','apaolini26@netlog.com','7 Lyons Terrace'),
    ('Flss Rudiger','frudiger27@livejournal.com','2 Lakewood Plaza'),
    ('Lorine Harrower','lharrower28@reddit.com','3235 Green Drive'),
    ('Carrissa Cleatherow','ccleatherow29@theatlantic.com','5787 Eggendart Circle'),
    ('Luther Killen','lkillen2a@rakuten.co.jp','65 Mariners Cove Center'),
    ('Sheelah Hovell','shovell2b@google.nl','7056 Graedel Place'),
    ('Filberte Robinette','frobinette2c@storify.com','98 Westridge Center'),
    ('Claire Rodinger','crodinger2d@webnode.com','32814 Bay Hill'),
    ('Carolyn Nettleship','cnettleship2e@squarespace.com','3 Tomscot Court'),
    ('Darcy Linden','dlinden2f@ed.gov','91311 Marcy Alley'),
    ('Waylin Pallister','wpallister2g@usatoday.com','86 Londonderry Drive'),
    ('Cate Le Hucquet','cle2h@w3.org','3 American Ash Center'),
    ('Marie-jeanne Tremblot','mtremblot2i@reuters.com','4178 Atwood Drive'),
    ('Rodrigo Decruse','rdecruse2j@pen.io','039 Lakeland Alley'),
    ('Griswold Caulwell','gcaulwell2k@springer.com','0 Esch Place'),
    ('Vasili Balnave','vbalnave2l@mayoclinic.com','4870 Vernon Trail'),
    ('Gilbertine Brundall','gbrundall2m@walmart.com','46 Vernon Hill'),
    ('Tova Faers','tfaers2n@hexun.com','52 Haas Avenue'),
    ('Marleen Salliss','msalliss2o@exblog.jp','1013 Vidon Alley'),
    ('Jarret Blazejewski','jblazejewski2p@cbsnews.com','267 Lawn Trail'),
    ('Deeyn Sproson','dsproson2q@istockphoto.com','914 International Court'),
    ('Friedrich Bernardon','fbernardon2r@homestead.com','4 Rieder Circle');

